---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flink-role
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - secrets
      - pods
      - secrets/finalizers
    verbs:
      - '*'
  - apiGroups:
      - daas.tenxcloud.com
    resources:
      - flinkclusters
    verbs:
      - '*'
  - apiGroups:
      - policy
      - extensions
    resourceNames:
      - system
      - default
    resources:
      - podsecuritypolicies
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flink-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flink-role
subjects:
  - kind: ServiceAccount
    name: flink-cluster-operator
