apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flink-cluster-operator
  namespace: flink-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flink-cluster-operator
subjects:
  - kind: ServiceAccount
    name: flink-cluster-operator
